language: java
sudo: false
notifications:
  slack:
    secure: guwQnPR2kdBfezhp2/0xR5uRNtm7IETKhgPw+T5eKAaWgvNoN8jG4HFtFhwo8my+Jml0RhsT1vUg4dpQEFWPFG2S/DY5GbvkJ78Pos7bda4efyjb2j0Gf+QR4S6h3J3SeLf0a2BRYNsoo3zWAWZ/ie66jQYCwnMppvufBHqCYAgk3HoYO/yfLLGfGmpld8wpCVDjZ9b6hVQgU+sFfna6GqVVez2u92M/zx2RD/cRljaNa3hB92Lr0CyipR4i4cD2zFi8XCfvk0f0mXvdB/gaaSWAf2eZtFopK9aWeOI6xPoJdp4eYpoMDmFuXxoDdOkzU6eUfc62ue450p/MsbGqfPiUfIdefnfXF0igmX7PVI11kPd/GD9YAdEMROTFz2hvHVY0Ngk3O9IK+JxVihNsvNLgg9ALIEswziWCsoa9hOZbGD9Hd29NaG4oVLeJt1Jhkbud66WC1apyMpDDP1Y6UaIN4EBjHeoJ9oOSXkClmTVb7U5H7ZexoMZys+wu/nWK02fipUI142H4OdXRGGHjypPh2H6M9su/voHKquoUnwsj5KszAl7PZnauPuyM+h/S5M5XxmLOgKZ0VTG2/7WMFjJHl08IzK5fZy0rBVW7vjLLXQxdMOGdk70I1lOwxxI9YXyLeun5c8aBOK8KKp6WFHoycjaSzsQRGx8zDHrG/Bc=
deploy:
  provider: releases
  api_key:
    secure: EQSCTToZoKJidEHvjRtV+KG1CJShGxMeoApSe9c/ErXVKMqAiKCSGMSj/Ww+XgoxQ6nl/NN18U9kpeK7u2gOhAypJCgW5HdWCLAIWJXrChW/BUi4Tqov42mG6havUB/I4TAqUmSAeYBNGoepDDPPzt5CsBqUKBIg9aKdihX5AsVMxx4LC+ATgm2vi+kQV81xaUxNSBG3+ePFbPKwTSt7l+pQqZof6euVlusoZOTfAFC/d/lC070hvV3W5znlh5mME0g0c402RfGzVUP5CxVC47DAkGwA9cbKV+FcgcOTbH42ESBlqvLJ1P+DfW0vGzRSDtAojOwBeHGHPi9ugjJEWhyYSWVtC5n/qCWdQdpDsuqFFLicWhzUrp76ZYK2mL8tNPdTTsL08+p4XhDmB+aVoP/yKUPkdcLYZJeALlIgnPhCBLgQLBUEZnOgbolKUEe351cb/DP+ln+Fi3wAPNHzQ47noFauDTAa2znj93AJXMAPcWPckbAC/pythqL5BeNDX0lBzKLWZbGjwTW92RZLkS2mrcvH3uzpWfG10Tb2I7xZTnmHpCYmjy7CQMsvR04MGDgjnrhWh0MMyoEWsv78apRTWebwvVcQE3kVy0UuRVozRqHg9rBKGGkLe2yjK2rDqJg/EaS8tGO5cOdJ2cAFGpl9ouOilLAgk/2VSvkScMs=
  file: build/distributions/xld-mule-mc-plugin-5.1.0-rc6.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-mule-mc-plugin
